#fonts
font=Iosevka:size=14:weight=bold:slant=oblique:style=Bold Italic
placeholder = "Software..."
prompt = "🔎"
message = "Select the software:"
message-mode = wrap
width = 50
[colors]
background=#120D1Eff
text=#D9D0E8ff
message=#F2EEF9ff
prompt=#C87DD4ff
placeholder=#352748ff
input=#C87DD4ff
match=#C87DD4ff
selection=#352748ff
selection-text=#F2EEF9ff
selection-match=#C87DD4ff
border=#352748ff

[border]
width = 5
radius = 35
selection-radius=7