#=====================================
#===PANSY====THEME======TOML==========
#=====================================


theme_name = "Pansy"
author = "Otr3bor"
version = "1.0.0"
#---------------------
#---------Style-------
#---------------------

#===Colors===
[colors.normal]
black =         "#1A1228"
red =           "#C94F6B"
green =         "#5A8A5E"
yellow =        "#C98A2A"
purple =        "#5C4BA0"
pink =          "#9B4FA6"
blue =          "#7A9EBF"
white =         "#D9D0E8"

[colors.bright]
black =         "#352748"
red =           "#E8718E"
green =         "#7ABF7E"
yellow =        "#F0B84A"
purple =        "#9580D6"
pink =          "#C87DD4"
blue =          "#A8C8E8"
white =         "#F2EEF9"

[colors.special]
background =    "#120D1E"
foreground =    "#D9D0E8"
icons =         "#C87DD4"

#===Terminal===

[tui.cursor]
shape =                 "beam"
shape_unfocused =       "hollow"
beam_thickness =        1.5
blink_interval =        -1
stop_blinking_after =   15.0
trail =                 200
trail_color =           "none"

[tui.window]
blur =                  1
opacity =               0.75


#===Fonts===
[font]
family =                "Iosevka"
bold =                  "auto"
italic =                "auto"
bold_italic =           "auto"
size =                  13


#---------------------
#-----Hyprland--------
#---------------------

#===Hyprland Specifics===
[hyprland.general]
gaps_in = 5
gaps_out = 20
border_size = 4
layout = "dwindle"
active_gradient = ["colors.normal.purple", "colors.bright.black"]
inactive_gradient = ["colors.normal.white", "colors.bright.purple"]
angle = 225
