local func = require("modules.functions")

hl.on("hyprland.start", function()
    hl.exec_cmd("kitty")
    hl.exec_cmd("kitty --hold -e cava &")
    hl.exec_cmd("kitty --hold -e tty-clock -c -C 5- &")
    hl.exec_cmd("swaync")
    hl.exec_cmd("udiskie &")
    hl.exec_cmd("fxitx5 &")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("quickshell")
    func.targetMonitor = func.targetMonitorUpdate(func.secondMonitor)
    func.updateState()
end)