# Pansy (the flower) colorscheme
background_opacity 0.75
background_blur 1

background            #120D1E
foreground            #D9D0E8
cursor                #C87DD4
cursor_text_color     #120D1E
selection_background  #352748
selection_foreground  #F2EEF9

# Normal
color0                 #1A1228
color1                 #C94F6B
color2                 #5A8A5E
color3                 #C98A2A
color4                 #5C4BA0
color5                 #9B4FA6
color6                 #7A9EBF
color7                 #D9D0E8

# Bright
color8                #352748
color9                #E8718E
color10               #7ABF7E
color11               #F0B84A
color12               #9580D6
color13               #C87DD4 
color14               #A8C8E8
color15               #F2EEF9

#other style settings
#cursor
cursor_shape beam
cursor_shape_unfocused hollow
cursor_beam_thickness 1.5
cursor_blink_interval -1
cursor_stop_blinking_after 15.0
#vvv so that it doesn't make some strange movement during the uwufetch startup
cursor_trail 200 
#cursor_trail_color #F0B84A (still not sure)
cursor_trail_color none
